#!/bin/bash
systemctl disable KootnetNetworkTestersServer
systemctl stop KootnetNetworkTestersServer
crontab -u root -r
find /opt/kootnet-network-testers -type d -name __pycache__ -exec rm -rf {} \; 2>/dev/null
exit 0
